# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('bed', models.IntegerField()),
                ('bath', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('squareMeters', models.IntegerField()),
                ('cordinate_x', models.IntegerField()),
                ('cordinate_y', models.IntegerField()),
                ('provinces', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
